//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDBS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceAgreement
    {
        public int Id { get; set; }
        public string ServiceTitle { get; set; }
        public byte State { get; set; }
        public byte DurationType { get; set; }
        public int SLAId { get; set; }
        public Nullable<int> MeterPointId { get; set; }
        public Nullable<int> ApplicableServiceId { get; set; }
        public Nullable<int> RankedTariffId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CrossRateTypeId { get; set; }
        public Nullable<byte> InstallmentPaymentDay { get; set; }
        public Nullable<bool> InstallmentEndOfMonth { get; set; }
        public Nullable<int> InstallmentTemplateId { get; set; }
        public Nullable<int> DebtDueTemplateId { get; set; }
        public Nullable<bool> IsAuthorizeEnabled { get; set; }
        public string TransferDocId { get; set; }
        public string TransferWebUrl { get; set; }
        public Nullable<int> ClassifierId { get; set; }
        public System.DateTime ObjectDate { get; set; }
        public bool IsCorrected { get; set; }
        public bool IsCorrection { get; set; }
        public System.DateTime RegDate { get; set; }
        public byte[] RowVersion { get; set; }
        public System.DateTime SysDate { get; set; }
        public string TransferInfo { get; set; }
    
        public virtual SLA SLA { get; set; }
    }
}
