//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDBS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SLA()
        {
            this.ServiceAgreements = new HashSet<ServiceAgreement>();
        }
    
        public int Id { get; set; }
        public string AdminNumber { get; set; }
        public byte State { get; set; }
        public byte FunctionType { get; set; }
        public byte OwnershipType { get; set; }
        public byte ServiceType { get; set; }
        public decimal TotalBalance { get; set; }
        public Nullable<decimal> RegularWarrantyDepositLimit { get; set; }
        public Nullable<decimal> FrozenWarrantyDepositLimit { get; set; }
        public Nullable<decimal> WarrantyLowLimit { get; set; }
        public string OldCustomerNumber { get; set; }
        public string Description { get; set; }
        public int GeneralContractId { get; set; }
        public Nullable<int> SupplyPointId { get; set; }
        public int ServiceUnitId { get; set; }
        public byte[] RowVersion { get; set; }
        public System.DateTime SysDate { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> IsInvoiceEnabled { get; set; }
        public Nullable<bool> SMSService { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceAgreement> ServiceAgreements { get; set; }
    }
}
